// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/frb_generated.dart';

/// Create a new sender session. Files will be imported into a blob store
/// at the given data directory.
///
/// Set `use_relay` to true for internet transfers (uses n0 relay servers).
/// Set to false for LAN-only transfers.
Future<RsIrohSender> irohSenderNew({
  required String dataDir,
  required bool useRelay,
}) => RustLib.instance.api.crateApiIrohTransferIrohSenderNew(
  dataDir: dataDir,
  useRelay: useRelay,
);

/// Import a file into the blob store. Returns "hash_hex:file_size".
Future<String> irohSenderImportFile({
  required RsIrohSender sender,
  required String filePath,
}) => RustLib.instance.api.crateApiIrohTransferIrohSenderImportFile(
  sender: sender,
  filePath: filePath,
);

/// Create a ticket for the imported collection.
///
/// `files_json` is a JSON array: [{"fileName":"...","size":123,"fileType":"...","hash":"...","lastModified":null}]
Future<String> irohSenderCreateTicket({
  required RsIrohSender sender,
  required String senderAlias,
  required String senderFingerprint,
  required String version,
  required String filesJson,
}) => RustLib.instance.api.crateApiIrohTransferIrohSenderCreateTicket(
  sender: sender,
  senderAlias: senderAlias,
  senderFingerprint: senderFingerprint,
  version: version,
  filesJson: filesJson,
);

/// Get the endpoint address as a JSON string.
Future<String> irohSenderEndpointAddr({required RsIrohSender sender}) =>
    RustLib.instance.api.crateApiIrohTransferIrohSenderEndpointAddr(sender: sender);

/// Start serving blobs in the background. Blocks until cancelled.
Future<void> irohSenderServe({required RsIrohSender sender}) => RustLib.instance.api.crateApiIrohTransferIrohSenderServe(sender: sender);

/// Cancel the sender session.
Future<void> irohSenderCancel({required RsIrohSender sender}) => RustLib.instance.api.crateApiIrohTransferIrohSenderCancel(sender: sender);

/// Shut down the sender and clean up the blob store.
Future<void> irohSenderShutdown({required RsIrohSender sender}) => RustLib.instance.api.crateApiIrohTransferIrohSenderShutdown(sender: sender);

/// Create a new receiver session.
Future<RsIrohReceiver> irohReceiverNew({required bool useRelay}) => RustLib.instance.api.crateApiIrohTransferIrohReceiverNew(useRelay: useRelay);

/// Fetch the collection metadata from the provider using the ticket.
/// Returns the LocalSendCollection as JSON.
Future<String> irohReceiverFetchCollection({
  required RsIrohReceiver receiver,
  required String ticket,
}) => RustLib.instance.api.crateApiIrohTransferIrohReceiverFetchCollection(
  receiver: receiver,
  ticket: ticket,
);

/// Download selected files from the provider.
///
/// `file_indices_json` is a JSON array of indices into the collection's file list.
/// `output_dir` is where files will be exported.
/// Returns total bytes downloaded.
Future<BigInt> irohReceiverDownload({
  required RsIrohReceiver receiver,
  required String ticket,
  required String fileIndicesJson,
  required String outputDir,
}) => RustLib.instance.api.crateApiIrohTransferIrohReceiverDownload(
  receiver: receiver,
  ticket: ticket,
  fileIndicesJson: fileIndicesJson,
  outputDir: outputDir,
);

/// Cancel the receiver session.
Future<void> irohReceiverCancel({required RsIrohReceiver receiver}) =>
    RustLib.instance.api.crateApiIrohTransferIrohReceiverCancel(receiver: receiver);

/// Shut down the receiver and clean up.
Future<void> irohReceiverShutdown({required RsIrohReceiver receiver}) =>
    RustLib.instance.api.crateApiIrohTransferIrohReceiverShutdown(receiver: receiver);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsIrohReceiver>>
abstract class RsIrohReceiver implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsIrohSender>>
abstract class RsIrohSender implements RustOpaqueInterface {}
