// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/frb_generated.dart';

/// Create a new sender session.
///
/// - `data_dir`: path for the blob store
/// - `use_relay`: true for internet transfers (n0 relay), false for LAN-only
Future<RsIrohSender> irohSenderNew({
  required String dataDir,
  required bool useRelay,
}) => RustLib.instance.api.crateApiIrohTransferIrohSenderNew(
  dataDir: dataDir,
  useRelay: useRelay,
);

/// Import a file into the blob store.
///
/// Handles `content://` URIs on Android by opening the SAF fd and creating
/// a `/proc/self/fd/N` path for zero-copy mmap import (no full-file read
/// into memory). Returns "hash_hex:file_size".
Future<String> irohSenderImportFile({
  required RsIrohSender sender,
  required String filePath,
}) => RustLib.instance.api.crateApiIrohTransferIrohSenderImportFile(
  sender: sender,
  filePath: filePath,
);

/// Start the sender: create a ticket from imported files, begin serving blobs,
/// and broadcast the ticket over multicast.
///
/// Spawns serving and announcing in background tokio tasks and returns
/// immediately with the ticket string.
///
/// `files_json`: JSON array of `LocalSendFileMeta` objects.
/// `sender_info_json`: JSON object with `alias`, `fingerprint`, `version`, `port`, `protocol` fields.
Future<String> irohSenderStart({
  required RsIrohSender sender,
  required String senderInfoJson,
  required String filesJson,
}) => RustLib.instance.api.crateApiIrohTransferIrohSenderStart(
  sender: sender,
  senderInfoJson: senderInfoJson,
  filesJson: filesJson,
);

/// Cancel the sender session (stops serving and announcing).
Future<void> irohSenderCancel({required RsIrohSender sender}) => RustLib.instance.api.crateApiIrohTransferIrohSenderCancel(sender: sender);

/// Create a new receiver session.
///
/// No peer discovery — the ticket comes from the Device model (IrohDiscovery)
/// which is populated by the existing Dart multicast listener.
Future<RsIrohReceiver> irohReceiverNew({required bool useRelay}) => RustLib.instance.api.crateApiIrohTransferIrohReceiverNew(useRelay: useRelay);

/// Fetch the collection metadata from a provider using a ticket.
///
/// `ticket`: the iroh ticket from a Device's IrohDiscovery (obtained via
/// the existing Dart multicast discovery flow).
/// Returns the `LocalSendCollection` as JSON (contains sender info + file list).
Future<String> irohReceiverFetchCollection({
  required RsIrohReceiver receiver,
  required String ticket,
}) => RustLib.instance.api.crateApiIrohTransferIrohReceiverFetchCollection(
  receiver: receiver,
  ticket: ticket,
);

/// Download selected files from the provider.
///
/// - `ticket`: the iroh ticket
/// - `file_indices_json`: JSON array of 0-based indices into the collection's file list
/// - `output_dir`: directory to save files to
/// Returns total bytes downloaded.
Future<BigInt> irohReceiverDownload({
  required RsIrohReceiver receiver,
  required String ticket,
  required String fileIndicesJson,
  required String outputDir,
}) => RustLib.instance.api.crateApiIrohTransferIrohReceiverDownload(
  receiver: receiver,
  ticket: ticket,
  fileIndicesJson: fileIndicesJson,
  outputDir: outputDir,
);

/// Cancel the receiver session.
Future<void> irohReceiverCancel({required RsIrohReceiver receiver}) =>
    RustLib.instance.api.crateApiIrohTransferIrohReceiverCancel(receiver: receiver);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsIrohReceiver>>
abstract class RsIrohReceiver implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsIrohSender>>
abstract class RsIrohSender implements RustOpaqueInterface {}
