// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/api/crypto.dart';
import 'package:localsend_app/rust/api/http.dart';
import 'package:localsend_app/rust/api/iroh_transfer.dart';
import 'package:localsend_app/rust/api/logging.dart';
import 'package:localsend_app/rust/api/model.dart';
import 'package:localsend_app/rust/api/stream.dart';
import 'package:localsend_app/rust/frb_generated.dart';
import 'package:localsend_app/rust/frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1833464994;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'rust_lib_localsend_app',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiStreamDart2RustStreamSinkAdd({
    required Dart2RustStreamSink that,
    required List<int> data,
  });

  Future<void> crateApiHttpRsHttpClientCancel({
    required RsHttpClient that,
    required ProtocolType protocol,
    required String ip,
    required int port,
    required String sessionId,
  });

  Future<PrepareUploadResult> crateApiHttpRsHttpClientPrepareUpload({
    required RsHttpClient that,
    required ProtocolType protocol,
    required String ip,
    required int port,
    required PrepareUploadRequestDto payload,
    String? publicKey,
    String? pin,
  });

  Future<ResultWithPublicKeyRegisterResponseDto> crateApiHttpRsHttpClientRegister({
    required RsHttpClient that,
    required ProtocolType protocol,
    required String ip,
    required int port,
    required RegisterDto payload,
  });

  Future<void> crateApiHttpRsHttpClientUpload({
    required RsHttpClient that,
    required ProtocolType protocol,
    required String ip,
    required int port,
    String? publicKey,
    required String sessionId,
    required String fileId,
    required String token,
    required Dart2RustStreamReceiver binary,
  });

  RsHttpClient crateApiHttpCreateClient({
    required String privateKey,
    required String cert,
    required LsHttpClientVersion version,
  });

  Future<(Dart2RustStreamSink, Dart2RustStreamReceiver)> crateApiStreamCreateStream();

  Future<void> crateApiLoggingEnableDebugLogging();

  Future<KeyPair> crateApiCryptoGenerateKeyPair();

  Future<void> crateApiIrohTransferIrohReceiverCancel({
    required RsIrohReceiver receiver,
  });

  Future<BigInt> crateApiIrohTransferIrohReceiverDownload({
    required RsIrohReceiver receiver,
    required String ticket,
    required String fileIndicesJson,
    required String outputDir,
  });

  Future<String> crateApiIrohTransferIrohReceiverFetchCollection({
    required RsIrohReceiver receiver,
    required String ticket,
  });

  Future<RsIrohReceiver> crateApiIrohTransferIrohReceiverNew({
    required bool useRelay,
  });

  Future<void> crateApiIrohTransferIrohSenderCancel({
    required RsIrohSender sender,
  });

  Future<String> crateApiIrohTransferIrohSenderImportFile({
    required RsIrohSender sender,
    required String filePath,
  });

  Future<RsIrohSender> crateApiIrohTransferIrohSenderNew({
    required String dataDir,
    required bool useRelay,
  });

  Future<String> crateApiIrohTransferIrohSenderStart({
    required RsIrohSender sender,
    required String senderInfoJson,
    required String filesJson,
  });

  Future<void> crateApiCryptoVerifyCert({
    required String cert,
    required String publicKey,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Dart2RustStreamReceiver;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Dart2RustStreamReceiver;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Dart2RustStreamReceiverPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Dart2RustStreamSink;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Dart2RustStreamSink;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Dart2RustStreamSinkPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_RsHttpClient;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_RsHttpClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RsHttpClientPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_RsIrohReceiver;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_RsIrohReceiver;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RsIrohReceiverPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_RsIrohSender;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_RsIrohSender;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RsIrohSenderPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiStreamDart2RustStreamSinkAdd({
    required Dart2RustStreamSink that,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStreamDart2RustStreamSinkAddConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStreamDart2RustStreamSinkAddConstMeta => const TaskConstMeta(
    debugName: 'Dart2RustStreamSink_add',
    argNames: ['that', 'data'],
  );

  @override
  Future<void> crateApiHttpRsHttpClientCancel({
    required RsHttpClient that,
    required ProtocolType protocol,
    required String ip,
    required int port,
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
            that,
            serializer,
          );
          sse_encode_protocol_type(protocol, serializer);
          sse_encode_String(ip, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_rs_http_client_error,
        ),
        constMeta: kCrateApiHttpRsHttpClientCancelConstMeta,
        argValues: [that, protocol, ip, port, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpRsHttpClientCancelConstMeta => const TaskConstMeta(
    debugName: 'RsHttpClient_cancel',
    argNames: ['that', 'protocol', 'ip', 'port', 'sessionId'],
  );

  @override
  Future<PrepareUploadResult> crateApiHttpRsHttpClientPrepareUpload({
    required RsHttpClient that,
    required ProtocolType protocol,
    required String ip,
    required int port,
    required PrepareUploadRequestDto payload,
    String? publicKey,
    String? pin,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
            that,
            serializer,
          );
          sse_encode_protocol_type(protocol, serializer);
          sse_encode_String(ip, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_box_autoadd_prepare_upload_request_dto(
            payload,
            serializer,
          );
          sse_encode_opt_String(publicKey, serializer);
          sse_encode_opt_String(pin, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_prepare_upload_result,
          decodeErrorData: sse_decode_rs_http_client_error,
        ),
        constMeta: kCrateApiHttpRsHttpClientPrepareUploadConstMeta,
        argValues: [that, protocol, ip, port, payload, publicKey, pin],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpRsHttpClientPrepareUploadConstMeta => const TaskConstMeta(
    debugName: 'RsHttpClient_prepare_upload',
    argNames: [
      'that',
      'protocol',
      'ip',
      'port',
      'payload',
      'publicKey',
      'pin',
    ],
  );

  @override
  Future<ResultWithPublicKeyRegisterResponseDto> crateApiHttpRsHttpClientRegister({
    required RsHttpClient that,
    required ProtocolType protocol,
    required String ip,
    required int port,
    required RegisterDto payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
            that,
            serializer,
          );
          sse_encode_protocol_type(protocol, serializer);
          sse_encode_String(ip, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_box_autoadd_register_dto(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_result_with_public_key_register_response_dto,
          decodeErrorData: sse_decode_rs_http_client_error,
        ),
        constMeta: kCrateApiHttpRsHttpClientRegisterConstMeta,
        argValues: [that, protocol, ip, port, payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpRsHttpClientRegisterConstMeta => const TaskConstMeta(
    debugName: 'RsHttpClient_register',
    argNames: ['that', 'protocol', 'ip', 'port', 'payload'],
  );

  @override
  Future<void> crateApiHttpRsHttpClientUpload({
    required RsHttpClient that,
    required ProtocolType protocol,
    required String ip,
    required int port,
    String? publicKey,
    required String sessionId,
    required String fileId,
    required String token,
    required Dart2RustStreamReceiver binary,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
            that,
            serializer,
          );
          sse_encode_protocol_type(protocol, serializer);
          sse_encode_String(ip, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_opt_String(publicKey, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(fileId, serializer);
          sse_encode_String(token, serializer);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
            binary,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_rs_http_client_error,
        ),
        constMeta: kCrateApiHttpRsHttpClientUploadConstMeta,
        argValues: [
          that,
          protocol,
          ip,
          port,
          publicKey,
          sessionId,
          fileId,
          token,
          binary,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpRsHttpClientUploadConstMeta => const TaskConstMeta(
    debugName: 'RsHttpClient_upload',
    argNames: [
      'that',
      'protocol',
      'ip',
      'port',
      'publicKey',
      'sessionId',
      'fileId',
      'token',
      'binary',
    ],
  );

  @override
  RsHttpClient crateApiHttpCreateClient({
    required String privateKey,
    required String cert,
    required LsHttpClientVersion version,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(privateKey, serializer);
          sse_encode_String(cert, serializer);
          sse_encode_ls_http_client_version(version, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient,
          decodeErrorData: sse_decode_rs_http_client_error,
        ),
        constMeta: kCrateApiHttpCreateClientConstMeta,
        argValues: [privateKey, cert, version],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpCreateClientConstMeta => const TaskConstMeta(
    debugName: 'create_client',
    argNames: ['privateKey', 'cert', 'version'],
  );

  @override
  Future<(Dart2RustStreamSink, Dart2RustStreamReceiver)> crateApiStreamCreateStream() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_sink_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_receiver,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStreamCreateStreamConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStreamCreateStreamConstMeta => const TaskConstMeta(
    debugName: 'create_stream',
    argNames: [],
  );

  @override
  Future<void> crateApiLoggingEnableDebugLogging() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLoggingEnableDebugLoggingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoggingEnableDebugLoggingConstMeta => const TaskConstMeta(
    debugName: 'enable_debug_logging',
    argNames: [],
  );

  @override
  Future<KeyPair> crateApiCryptoGenerateKeyPair() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_pair,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoGenerateKeyPairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateKeyPairConstMeta => const TaskConstMeta(
    debugName: 'generate_key_pair',
    argNames: [],
  );

  @override
  Future<void> crateApiIrohTransferIrohReceiverCancel({
    required RsIrohReceiver receiver,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
            receiver,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrohTransferIrohReceiverCancelConstMeta,
        argValues: [receiver],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohTransferIrohReceiverCancelConstMeta => const TaskConstMeta(
    debugName: 'iroh_receiver_cancel',
    argNames: ['receiver'],
  );

  @override
  Future<BigInt> crateApiIrohTransferIrohReceiverDownload({
    required RsIrohReceiver receiver,
    required String ticket,
    required String fileIndicesJson,
    required String outputDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
            receiver,
            serializer,
          );
          sse_encode_String(ticket, serializer);
          sse_encode_String(fileIndicesJson, serializer);
          sse_encode_String(outputDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrohTransferIrohReceiverDownloadConstMeta,
        argValues: [receiver, ticket, fileIndicesJson, outputDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohTransferIrohReceiverDownloadConstMeta => const TaskConstMeta(
    debugName: 'iroh_receiver_download',
    argNames: ['receiver', 'ticket', 'fileIndicesJson', 'outputDir'],
  );

  @override
  Future<String> crateApiIrohTransferIrohReceiverFetchCollection({
    required RsIrohReceiver receiver,
    required String ticket,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
            receiver,
            serializer,
          );
          sse_encode_String(ticket, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrohTransferIrohReceiverFetchCollectionConstMeta,
        argValues: [receiver, ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohTransferIrohReceiverFetchCollectionConstMeta => const TaskConstMeta(
    debugName: 'iroh_receiver_fetch_collection',
    argNames: ['receiver', 'ticket'],
  );

  @override
  Future<RsIrohReceiver> crateApiIrohTransferIrohReceiverNew({
    required bool useRelay,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(useRelay, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrohTransferIrohReceiverNewConstMeta,
        argValues: [useRelay],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohTransferIrohReceiverNewConstMeta => const TaskConstMeta(
    debugName: 'iroh_receiver_new',
    argNames: ['useRelay'],
  );

  @override
  Future<void> crateApiIrohTransferIrohSenderCancel({
    required RsIrohSender sender,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
            sender,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrohTransferIrohSenderCancelConstMeta,
        argValues: [sender],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohTransferIrohSenderCancelConstMeta => const TaskConstMeta(
    debugName: 'iroh_sender_cancel',
    argNames: ['sender'],
  );

  @override
  Future<String> crateApiIrohTransferIrohSenderImportFile({
    required RsIrohSender sender,
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
            sender,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrohTransferIrohSenderImportFileConstMeta,
        argValues: [sender, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohTransferIrohSenderImportFileConstMeta => const TaskConstMeta(
    debugName: 'iroh_sender_import_file',
    argNames: ['sender', 'filePath'],
  );

  @override
  Future<RsIrohSender> crateApiIrohTransferIrohSenderNew({
    required String dataDir,
    required bool useRelay,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          sse_encode_bool(useRelay, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrohTransferIrohSenderNewConstMeta,
        argValues: [dataDir, useRelay],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohTransferIrohSenderNewConstMeta => const TaskConstMeta(
    debugName: 'iroh_sender_new',
    argNames: ['dataDir', 'useRelay'],
  );

  @override
  Future<String> crateApiIrohTransferIrohSenderStart({
    required RsIrohSender sender,
    required String senderInfoJson,
    required String filesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
            sender,
            serializer,
          );
          sse_encode_String(senderInfoJson, serializer);
          sse_encode_String(filesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIrohTransferIrohSenderStartConstMeta,
        argValues: [sender, senderInfoJson, filesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohTransferIrohSenderStartConstMeta => const TaskConstMeta(
    debugName: 'iroh_sender_start',
    argNames: ['sender', 'senderInfoJson', 'filesJson'],
  );

  @override
  Future<void> crateApiCryptoVerifyCert({
    required String cert,
    required String publicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cert, serializer);
          sse_encode_String(publicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoVerifyCertConstMeta,
        argValues: [cert, publicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoVerifyCertConstMeta => const TaskConstMeta(
    debugName: 'verify_cert',
    argNames: ['cert', 'publicKey'],
  );

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Dart2RustStreamReceiver =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Dart2RustStreamReceiver =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Dart2RustStreamSink =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Dart2RustStreamSink =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_RsHttpClient =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_RsHttpClient =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_RsIrohReceiver =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_RsIrohReceiver =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_RsIrohSender =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_RsIrohSender =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Dart2RustStreamReceiver dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Dart2RustStreamReceiverImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  Dart2RustStreamSink dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Dart2RustStreamSinkImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsHttpClient dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsHttpClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsIrohReceiver dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsIrohReceiverImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsIrohSender dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsIrohSenderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Dart2RustStreamSink dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Dart2RustStreamSinkImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsHttpClient dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsHttpClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsIrohReceiver dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsIrohReceiverImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsIrohSender dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsIrohSenderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  Map<String, FileDto> dco_decode_Map_String_file_dto_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_file_dto(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  Dart2RustStreamReceiver dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Dart2RustStreamReceiverImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  Dart2RustStreamSink dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Dart2RustStreamSinkImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsHttpClient dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsHttpClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsIrohReceiver dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsIrohReceiverImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RsIrohSender dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsIrohSenderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DeviceType dco_decode_box_autoadd_device_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_device_type(raw);
  }

  @protected
  FileMetadata dco_decode_box_autoadd_file_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_file_metadata(raw);
  }

  @protected
  PrepareUploadRequestDto dco_decode_box_autoadd_prepare_upload_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_prepare_upload_request_dto(raw);
  }

  @protected
  PrepareUploadResponseDto dco_decode_box_autoadd_prepare_upload_response_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_prepare_upload_response_dto(raw);
  }

  @protected
  RegisterDto dco_decode_box_autoadd_register_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_register_dto(raw);
  }

  @protected
  DeviceType dco_decode_device_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DeviceType.values[raw as int];
  }

  @protected
  FileDto dco_decode_file_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FileDto(
      id: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
      fileType: dco_decode_String(arr[3]),
      sha256: dco_decode_opt_String(arr[4]),
      preview: dco_decode_opt_String(arr[5]),
      metadata: dco_decode_opt_box_autoadd_file_metadata(arr[6]),
    );
  }

  @protected
  FileMetadata dco_decode_file_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FileMetadata(
      modified: dco_decode_opt_String(arr[0]),
      accessed: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  KeyPair dco_decode_key_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyPair(
      privateKey: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, FileDto)> dco_decode_list_record_string_file_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_file_dto).toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  LsHttpClientVersion dco_decode_ls_http_client_version(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LsHttpClientVersion.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DeviceType? dco_decode_opt_box_autoadd_device_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_device_type(raw);
  }

  @protected
  FileMetadata? dco_decode_opt_box_autoadd_file_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_file_metadata(raw);
  }

  @protected
  PrepareUploadResponseDto? dco_decode_opt_box_autoadd_prepare_upload_response_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_prepare_upload_response_dto(raw);
  }

  @protected
  PrepareUploadRequestDto dco_decode_prepare_upload_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PrepareUploadRequestDto(
      info: dco_decode_register_dto(arr[0]),
      files: dco_decode_Map_String_file_dto_None(arr[1]),
    );
  }

  @protected
  PrepareUploadResponseDto dco_decode_prepare_upload_response_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PrepareUploadResponseDto(
      sessionId: dco_decode_String(arr[0]),
      files: dco_decode_Map_String_String_None(arr[1]),
    );
  }

  @protected
  PrepareUploadResult dco_decode_prepare_upload_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PrepareUploadResult(
      statusCode: dco_decode_u_16(arr[0]),
      response: dco_decode_opt_box_autoadd_prepare_upload_response_dto(arr[1]),
    );
  }

  @protected
  ProtocolType dco_decode_protocol_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProtocolType.values[raw as int];
  }

  @protected
  (Dart2RustStreamSink, Dart2RustStreamReceiver)
  dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_sink_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_receiver(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
        arr[0],
      ),
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
        arr[1],
      ),
    );
  }

  @protected
  (String, FileDto) dco_decode_record_string_file_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_file_dto(arr[1]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  RegisterDto dco_decode_register_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8) throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RegisterDto(
      alias: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      deviceModel: dco_decode_opt_String(arr[2]),
      deviceType: dco_decode_opt_box_autoadd_device_type(arr[3]),
      token: dco_decode_String(arr[4]),
      port: dco_decode_u_16(arr[5]),
      protocol: dco_decode_protocol_type(arr[6]),
      hasWebInterface: dco_decode_bool(arr[7]),
    );
  }

  @protected
  RegisterResponseDto dco_decode_register_response_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RegisterResponseDto(
      alias: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      deviceModel: dco_decode_opt_String(arr[2]),
      deviceType: dco_decode_opt_box_autoadd_device_type(arr[3]),
      token: dco_decode_String(arr[4]),
      hasWebInterface: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ResultWithPublicKeyRegisterResponseDto dco_decode_result_with_public_key_register_response_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ResultWithPublicKeyRegisterResponseDto(
      publicKey: dco_decode_opt_String(arr[0]),
      body: dco_decode_register_response_dto(arr[1]),
    );
  }

  @protected
  RsHttpClientError dco_decode_rs_http_client_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return RsHttpClientError_StatusCode(
          status: dco_decode_u_16(raw[1]),
          message: dco_decode_opt_String(raw[2]),
        );
      case 1:
        return RsHttpClientError_Reqwest(
          dco_decode_String(raw[1]),
        );
      case 2:
        return RsHttpClientError_Json(
          dco_decode_String(raw[1]),
        );
      case 3:
        return RsHttpClientError_Io(
          dco_decode_String(raw[1]),
        );
      case 4:
        return RsHttpClientError_Other(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception('unreachable');
    }
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Dart2RustStreamReceiver sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Dart2RustStreamReceiverImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Dart2RustStreamSink sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Dart2RustStreamSinkImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsHttpClient sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsHttpClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsIrohReceiver sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsIrohReceiverImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsIrohSender sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsIrohSenderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Dart2RustStreamSink sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Dart2RustStreamSinkImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsHttpClient sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsHttpClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsIrohReceiver sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsIrohReceiverImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsIrohSender sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsIrohSenderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  Map<String, FileDto> sse_decode_Map_String_file_dto_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_file_dto(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  Dart2RustStreamReceiver sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Dart2RustStreamReceiverImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Dart2RustStreamSink sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Dart2RustStreamSinkImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsHttpClient sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsHttpClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsIrohReceiver sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsIrohReceiverImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RsIrohSender sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RsIrohSenderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DeviceType sse_decode_box_autoadd_device_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_device_type(deserializer));
  }

  @protected
  FileMetadata sse_decode_box_autoadd_file_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_file_metadata(deserializer));
  }

  @protected
  PrepareUploadRequestDto sse_decode_box_autoadd_prepare_upload_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_prepare_upload_request_dto(deserializer));
  }

  @protected
  PrepareUploadResponseDto sse_decode_box_autoadd_prepare_upload_response_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_prepare_upload_response_dto(deserializer));
  }

  @protected
  RegisterDto sse_decode_box_autoadd_register_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_register_dto(deserializer));
  }

  @protected
  DeviceType sse_decode_device_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DeviceType.values[inner];
  }

  @protected
  FileDto sse_decode_file_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_fileType = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_opt_String(deserializer);
    var var_preview = sse_decode_opt_String(deserializer);
    var var_metadata = sse_decode_opt_box_autoadd_file_metadata(deserializer);
    return FileDto(
      id: var_id,
      fileName: var_fileName,
      size: var_size,
      fileType: var_fileType,
      sha256: var_sha256,
      preview: var_preview,
      metadata: var_metadata,
    );
  }

  @protected
  FileMetadata sse_decode_file_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modified = sse_decode_opt_String(deserializer);
    var var_accessed = sse_decode_opt_String(deserializer);
    return FileMetadata(modified: var_modified, accessed: var_accessed);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  KeyPair sse_decode_key_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateKey = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    return KeyPair(privateKey: var_privateKey, publicKey: var_publicKey);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, FileDto)> sse_decode_list_record_string_file_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, FileDto)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_file_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  LsHttpClientVersion sse_decode_ls_http_client_version(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LsHttpClientVersion.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DeviceType? sse_decode_opt_box_autoadd_device_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_device_type(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FileMetadata? sse_decode_opt_box_autoadd_file_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_file_metadata(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PrepareUploadResponseDto? sse_decode_opt_box_autoadd_prepare_upload_response_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_prepare_upload_response_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PrepareUploadRequestDto sse_decode_prepare_upload_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_info = sse_decode_register_dto(deserializer);
    var var_files = sse_decode_Map_String_file_dto_None(deserializer);
    return PrepareUploadRequestDto(info: var_info, files: var_files);
  }

  @protected
  PrepareUploadResponseDto sse_decode_prepare_upload_response_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_files = sse_decode_Map_String_String_None(deserializer);
    return PrepareUploadResponseDto(sessionId: var_sessionId, files: var_files);
  }

  @protected
  PrepareUploadResult sse_decode_prepare_upload_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_statusCode = sse_decode_u_16(deserializer);
    var var_response = sse_decode_opt_box_autoadd_prepare_upload_response_dto(
      deserializer,
    );
    return PrepareUploadResult(
      statusCode: var_statusCode,
      response: var_response,
    );
  }

  @protected
  ProtocolType sse_decode_protocol_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProtocolType.values[inner];
  }

  @protected
  (Dart2RustStreamSink, Dart2RustStreamReceiver)
  sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_sink_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_receiver(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
      deserializer,
    );
    var var_field1 = sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
      deserializer,
    );
    return (var_field0, var_field1);
  }

  @protected
  (String, FileDto) sse_decode_record_string_file_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_file_dto(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RegisterDto sse_decode_register_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_alias = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_deviceModel = sse_decode_opt_String(deserializer);
    var var_deviceType = sse_decode_opt_box_autoadd_device_type(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_protocol = sse_decode_protocol_type(deserializer);
    var var_hasWebInterface = sse_decode_bool(deserializer);
    return RegisterDto(
      alias: var_alias,
      version: var_version,
      deviceModel: var_deviceModel,
      deviceType: var_deviceType,
      token: var_token,
      port: var_port,
      protocol: var_protocol,
      hasWebInterface: var_hasWebInterface,
    );
  }

  @protected
  RegisterResponseDto sse_decode_register_response_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_alias = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_deviceModel = sse_decode_opt_String(deserializer);
    var var_deviceType = sse_decode_opt_box_autoadd_device_type(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_hasWebInterface = sse_decode_bool(deserializer);
    return RegisterResponseDto(
      alias: var_alias,
      version: var_version,
      deviceModel: var_deviceModel,
      deviceType: var_deviceType,
      token: var_token,
      hasWebInterface: var_hasWebInterface,
    );
  }

  @protected
  ResultWithPublicKeyRegisterResponseDto sse_decode_result_with_public_key_register_response_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_opt_String(deserializer);
    var var_body = sse_decode_register_response_dto(deserializer);
    return ResultWithPublicKeyRegisterResponseDto(
      publicKey: var_publicKey,
      body: var_body,
    );
  }

  @protected
  RsHttpClientError sse_decode_rs_http_client_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_status = sse_decode_u_16(deserializer);
        var var_message = sse_decode_opt_String(deserializer);
        return RsHttpClientError_StatusCode(
          status: var_status,
          message: var_message,
        );
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return RsHttpClientError_Reqwest(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return RsHttpClientError_Json(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return RsHttpClientError_Io(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return RsHttpClientError_Other(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    Dart2RustStreamReceiver self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Dart2RustStreamReceiverImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    Dart2RustStreamSink self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Dart2RustStreamSinkImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    RsHttpClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsHttpClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    RsIrohReceiver self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsIrohReceiverImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    RsIrohSender self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsIrohSenderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    Dart2RustStreamSink self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Dart2RustStreamSinkImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    RsHttpClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsHttpClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    RsIrohReceiver self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsIrohReceiverImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    RsIrohSender self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsIrohSenderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_file_dto_None(
    Map<String, FileDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_file_dto(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    Dart2RustStreamReceiver self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Dart2RustStreamReceiverImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    Dart2RustStreamSink self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Dart2RustStreamSinkImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    RsHttpClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsHttpClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohReceiver(
    RsIrohReceiver self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsIrohReceiverImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsIrohSender(
    RsIrohSender self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RsIrohSenderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_device_type(
    DeviceType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_device_type(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_file_metadata(
    FileMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_file_metadata(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_prepare_upload_request_dto(
    PrepareUploadRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_prepare_upload_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_prepare_upload_response_dto(
    PrepareUploadResponseDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_prepare_upload_response_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_register_dto(
    RegisterDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_register_dto(self, serializer);
  }

  @protected
  void sse_encode_device_type(DeviceType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_file_dto(FileDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_String(self.fileType, serializer);
    sse_encode_opt_String(self.sha256, serializer);
    sse_encode_opt_String(self.preview, serializer);
    sse_encode_opt_box_autoadd_file_metadata(self.metadata, serializer);
  }

  @protected
  void sse_encode_file_metadata(FileMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.modified, serializer);
    sse_encode_opt_String(self.accessed, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_key_pair(KeyPair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.privateKey, serializer);
    sse_encode_String(self.publicKey, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_file_dto(
    List<(String, FileDto)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_file_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_ls_http_client_version(
    LsHttpClientVersion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_device_type(
    DeviceType? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_device_type(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_file_metadata(
    FileMetadata? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_file_metadata(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_prepare_upload_response_dto(
    PrepareUploadResponseDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_prepare_upload_response_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_prepare_upload_request_dto(
    PrepareUploadRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_register_dto(self.info, serializer);
    sse_encode_Map_String_file_dto_None(self.files, serializer);
  }

  @protected
  void sse_encode_prepare_upload_response_dto(
    PrepareUploadResponseDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_Map_String_String_None(self.files, serializer);
  }

  @protected
  void sse_encode_prepare_upload_result(
    PrepareUploadResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.statusCode, serializer);
    sse_encode_opt_box_autoadd_prepare_upload_response_dto(
      self.response,
      serializer,
    );
  }

  @protected
  void sse_encode_protocol_type(ProtocolType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void
  sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_sink_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_receiver(
    (Dart2RustStreamSink, Dart2RustStreamReceiver) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
      self.$1,
      serializer,
    );
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
      self.$2,
      serializer,
    );
  }

  @protected
  void sse_encode_record_string_file_dto(
    (String, FileDto) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_file_dto(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_register_dto(RegisterDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.alias, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_opt_String(self.deviceModel, serializer);
    sse_encode_opt_box_autoadd_device_type(self.deviceType, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_protocol_type(self.protocol, serializer);
    sse_encode_bool(self.hasWebInterface, serializer);
  }

  @protected
  void sse_encode_register_response_dto(
    RegisterResponseDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.alias, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_opt_String(self.deviceModel, serializer);
    sse_encode_opt_box_autoadd_device_type(self.deviceType, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_bool(self.hasWebInterface, serializer);
  }

  @protected
  void sse_encode_result_with_public_key_register_response_dto(
    ResultWithPublicKeyRegisterResponseDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.publicKey, serializer);
    sse_encode_register_response_dto(self.body, serializer);
  }

  @protected
  void sse_encode_rs_http_client_error(
    RsHttpClientError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case RsHttpClientError_StatusCode(
        status: final status,
        message: final message,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_u_16(status, serializer);
        sse_encode_opt_String(message, serializer);
      case RsHttpClientError_Reqwest(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case RsHttpClientError_Json(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case RsHttpClientError_Io(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case RsHttpClientError_Other(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class Dart2RustStreamReceiverImpl extends RustOpaque implements Dart2RustStreamReceiver {
  // Not to be used by end users
  Dart2RustStreamReceiverImpl.frbInternalDcoDecode(List<dynamic> wire) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Dart2RustStreamReceiverImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_Dart2RustStreamReceiver,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_Dart2RustStreamReceiver,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_Dart2RustStreamReceiverPtr,
  );
}

@sealed
class Dart2RustStreamSinkImpl extends RustOpaque implements Dart2RustStreamSink {
  // Not to be used by end users
  Dart2RustStreamSinkImpl.frbInternalDcoDecode(List<dynamic> wire) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Dart2RustStreamSinkImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_Dart2RustStreamSink,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_Dart2RustStreamSink,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_Dart2RustStreamSinkPtr,
  );

  Future<void> add({required List<int> data}) => RustLib.instance.api.crateApiStreamDart2RustStreamSinkAdd(that: this, data: data);
}

@sealed
class RsHttpClientImpl extends RustOpaque implements RsHttpClient {
  // Not to be used by end users
  RsHttpClientImpl.frbInternalDcoDecode(List<dynamic> wire) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RsHttpClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_RsHttpClient,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_RsHttpClient,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_RsHttpClientPtr,
  );

  Future<void> cancel({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required String sessionId,
  }) => RustLib.instance.api.crateApiHttpRsHttpClientCancel(
    that: this,
    protocol: protocol,
    ip: ip,
    port: port,
    sessionId: sessionId,
  );

  Future<PrepareUploadResult> prepareUpload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required PrepareUploadRequestDto payload,
    String? publicKey,
    String? pin,
  }) => RustLib.instance.api.crateApiHttpRsHttpClientPrepareUpload(
    that: this,
    protocol: protocol,
    ip: ip,
    port: port,
    payload: payload,
    publicKey: publicKey,
    pin: pin,
  );

  Future<ResultWithPublicKeyRegisterResponseDto> register({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required RegisterDto payload,
  }) => RustLib.instance.api.crateApiHttpRsHttpClientRegister(
    that: this,
    protocol: protocol,
    ip: ip,
    port: port,
    payload: payload,
  );

  Future<void> upload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    String? publicKey,
    required String sessionId,
    required String fileId,
    required String token,
    required Dart2RustStreamReceiver binary,
  }) => RustLib.instance.api.crateApiHttpRsHttpClientUpload(
    that: this,
    protocol: protocol,
    ip: ip,
    port: port,
    publicKey: publicKey,
    sessionId: sessionId,
    fileId: fileId,
    token: token,
    binary: binary,
  );
}

@sealed
class RsIrohReceiverImpl extends RustOpaque implements RsIrohReceiver {
  // Not to be used by end users
  RsIrohReceiverImpl.frbInternalDcoDecode(List<dynamic> wire) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RsIrohReceiverImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_RsIrohReceiver,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_RsIrohReceiver,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_RsIrohReceiverPtr,
  );
}

@sealed
class RsIrohSenderImpl extends RustOpaque implements RsIrohSender {
  // Not to be used by end users
  RsIrohSenderImpl.frbInternalDcoDecode(List<dynamic> wire) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RsIrohSenderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_RsIrohSender,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_RsIrohSender,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_RsIrohSenderPtr,
  );
}
